# fly.toml app configuration file generated for odin-book-api-empty-waterfall-5146 on 2024-08-30T00:45:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'odin-book-api-empty-waterfall-5146'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
